### ISSUE TITLE
O Próximo passo

### ISSUE THREAD

**Issue by Arthur-Rosa** [Victor23HD/OliveiraBookstore#6]
Podemos adicionar um Front-end para a aplicação, com uma parte total front, com acesso administrativo para gerenciar os livros, o que acha ?

Podemos ampliar mais também a aplicação node.

Estou disposto a ajudar!

**Comment by Victor23HD** [comment]
Opa Arthur!

Claro! Estou trabalhando na versão 2.0_(BigBrother) mas gostaria muito de expandir o CRUD pro front.

Me manda mensagem no linkedin: https://www.linkedin.com/notifications/?filter=all

Gostaria de entender um pouco mais sobre suas ideias.

Mr. Oliveira
